export const allActions = {
    SAVE_USER: 'SAVE_USER',
    DELETE_USER: 'DELETE_USER',
    AUTH_USER: 'AUTH_USER',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    UPDATE_PASSWORD_TOKEN: 'UPDATE_PASSWORD_BY_TOKEN',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD'
};
